### ISSUE TITLE
error after packaging

### ISSUE THREAD

**Issue by 0mkara** [0mkara/ethcode#23]
```
module.js:545
    throw err;
    ^

Error: Cannot find module 'solc'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/0mkar/.vscode/extensions/mathcody.ethcode-0.0.3/build/ext-src/worker.js:40:12)
    at Object.<anonymous> (/home/0mkar/.vscode/extensions/mathcody.ethcode-0.0.3/build/ext-src/worker.js:198:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
```

**Comment by 0mkara** [comment]
#24
